### PR TITLE
add: user auth in the RethinkDB provider

### PR DESCRIPTION
**Pull request by Emy**
I added the auth attributes "user" and "password".
I spent some time to look up how to authenticate with "rethinkdbash" so I thought it would be easier for other users of this provider to instantly see what's going on. I also added the default credentials for the admin user which are usually admin:''.

If this is redundant deny the PR and close :)

### CODE REVIEW

**Comment by kyranet** [comment]
Does this work with a fresh set-up in RethinkDB? The DB throws an error if the user is not found or if the password is invalid

**Comment by Emy** [comment]
```
The admin user

A new RethinkDB cluster always has one user named admin; 
this user always has all permissions at a global scope, and the user cannot be deleted. 
By default, the admin user has no password. 
You can change this by updating the admin user document, 
or by specifying the --initial-password command line option on startup.
```

In theory it should work according to: https://rethinkdb.com/docs/permissions-and-accounts/
But I'll go ahead and test it on a fresh DB.

**Comment by kyranet** [comment]
For the empty password, `''` instead of `null` works fine?

**Comment by Emy** [comment]
Unfortunately not since it explicitly expects a string as seen in:

``var cacheKey = self.password.toString("base64")+','+salt.toString("base64")+','+iterations;
TypeError: Cannot read property 'toString' of null
``

**Comment by kyranet** [comment]
TIL, thanks for your fast response and your contribution, merging now! ❤️

**Pull request merged**
