### PR TITLE
Fix image errors on cat.js by switching API

### PR DESCRIPTION
**Pull request by Dwigoric**

### CODE REVIEW

**Comment by BannerBomb** [comment]
I went to the url you changed it too but it only shows one cat image and gif no matter how many times I reload the page. :thinking:

**Comment by Dwigoric** [comment]
@BannerBomb You have to do a full refresh on the page to get a new image or GIF; unless the request is made from the app itself, not from a web browser.

**Comment by kyranet** [comment]
Hey, is this API still working?

**Comment by vladfrangu** [comment]
I don't see the need to replace an API that, right now, works just fine...

**Comment by Dwigoric** [comment]
No one is having issues with the current API, this could be only on my side.

**Pull request closed without merging**
