### PR TITLE
User clean up

### PR DESCRIPTION
**Pull request by Tylertron1998**
Use this for cleaning up the DB for users who have deleted there accounts.

### CODE REVIEW

**Comment by Soumil07** [comment]
This task isn't used anywhere. Are you sure you want it that way? Most users won't even know it's there. I would recommend initializing in klasaReady with a recurring time as a client option.

**Comment by tech6hutch** [comment]
How would you do that? This is the Klasa Pieces repo. Unless you literally mean `this.client.once('klasaReady', ...`

**Comment by Soumil07** [comment]
I'm dumb. Thought this was klasa repo.

**Comment by kyranet** [comment]
This piece is not suitable for production and does not work (as you would intend). Plus, this piece basically spams the API.

**Pull request closed without merging**
