### PR TITLE
Create eslintrc.json

### PR DESCRIPTION
**Pull request by OzcanOktay**

### CODE REVIEW

**Comment by OzcanOktay** [comment]
hi

**Comment by OzcanOktay** [comment]
waiting

**Comment by PyroTechniac** [comment]
There already is a .eslintrc.json, which uses a custom ruleset made for klasa and it's counterparts

**Comment by UnseenFaith** [comment]
https://github.com/dirigeants/klasa-lint

You can find all of our lint for pretty much everything in this repository.

**Pull request closed without merging**
