### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by InkoHX**

### CODE REVIEW

**Comment by kyranet** [comment]
@yuta0801 since you're the one who wrote that line, can you verify if it's correct, please?

**Comment by yuta0801** [comment]
This fix is not completely wrong, but it is an ambiguous sentence.
If translate it directly to English, it is  `Displays the invite link of the bot.`.

IMO: Originally it was grammatically a bit unnatural so it may be good to fix to `ボットの公式サーバーへの招待リンクを表示します。`
(directly translation: `Displays the invite link to an official server of the bot.`)

**Comment by MrJacz** [comment]
@yuta0801 yeah invite is to invite the bot to a server so the 2nd one would be incorrect

**Comment by yuta0801** [comment]
Umm... I found `join guild link` in the original text

```js
			COMMAND_INVITE_DESCRIPTION: 'Displays the join guild link of the bot.',
```

https://github.com/dirigeants/klasa/blob/master/src/languages/en-US.js#L118

**Comment by kyranet** [comment]
So, is @InkoHX's description correct? Just making sure.

**Comment by yuta0801** [comment]
At least I feel like the bot's own invite (OAuth) URL, rather than the server (guild) invite URL in that sentence.

**Comment by kyranet** [comment]
We updated the en-US file to clarify the line as of https://github.com/dirigeants/klasa/pull/693, thanks you for the suggestion.

**Comment by yuta0801** [comment]
Oh, okay. He's correct from the beginning.
I got hung up on the original "join guild link" and I did not check the command... sry

This might as well to follow original.

**Comment by kyranet** [comment]
Just double-checking before merging, this is correct now, right?

**Comment by yuta0801** [comment]
Yes, this is correct.

**Pull request merged**
