### PR TITLE
Added INHIBITOR_NSFW and COMMAND_CONF_GUARDED in fr-FR

### PR DESCRIPTION
**Pull request by Pandraghon**

### CODE REVIEW

**Comment by Pandraghon** [comment]
Should I use the changes made in #SettingGateway-Rewrite as well?

**Comment by kyranet** [comment]
SGv2 changes are done in another PR.

**Comment by Pandraghon** [comment]
I mean the fr-FR-related changes

**Comment by kyranet** [comment]
Nah, it's fine.

**Pull request merged**
