### PR TITLE
added Task Translation to de-DE language JSON

### PR DESCRIPTION
**Pull request by Dev-Yukine**
pretty much what the title say

### CODE REVIEW

**Comment by Pandraghon** [comment]
Might have conflicts with https://github.com/dirigeants/klasa-pieces/pull/37

**Comment by Dev-Yukine** [comment]
well then you might wanna add this in your PR or remove that from your PR so mine can get merged, your choice @Pandraghon

**Comment by Pandraghon** [comment]
@tech6hutch

**Comment by Dev-Yukine** [comment]
Closed in favor of another big PR

**Pull request closed without merging**
